//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EnquiryForm
    {
        public int Id { get; set; }
        public string LeadName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string ProfessionalDetails { get; set; }
        public string Qualification { get; set; }
        public string Yearofpassedout { get; set; }
        public string Workexpdomain { get; set; }
        public string Product { get; set; }
        public string Preferredlocation { get; set; }
        public string Prefbatch { get; set; }
        public string Reference { get; set; }
        public string Wanttojoin { get; set; }
        public string WantSMSAlerts { get; set; }
        public string LeadAssignedby { get; set; }
        public string Status { get; set; }
        public string LeadAssignedTo { get; set; }
        public string Record_CreatedBy { get; set; }
        public string Record_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Website { get; set; }
        public string Industry { get; set; }
        public string Rating { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public string LeadOwner { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public Nullable<System.DateTime> FollowUpdate { get; set; }
        public string CommentsForAssignment { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<int> SelectedProductId { get; set; }
        public Nullable<int> SelectedStatusId { get; set; }
        public Nullable<int> SelectedReference { get; set; }
        public string WantMailAlerts { get; set; }
        public Nullable<int> Wantsmsalertsid { get; set; }
        public Nullable<int> Wantemailalertsid { get; set; }
    }
}
