//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLog
    {
        public int LogId { get; set; }
        public string UserName { get; set; }
        public string OrgName { get; set; }
        public string ScreenName { get; set; }
        public Nullable<System.DateTime> LogDatetime { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
    }
}
