//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Enquirytracking
    {
        public int track_enq_Id { get; set; }
        public int track_parent_enq_Id { get; set; }
        public string track_LeadName { get; set; }
        public string track_Address { get; set; }
        public string track_Mobile { get; set; }
        public string track_Email { get; set; }
        public string track_ProfessionalDetails { get; set; }
        public string track_Qualification { get; set; }
        public string track_Yearofpassedout { get; set; }
        public string track_Workexpdomain { get; set; }
        public string track_Product { get; set; }
        public string track_Preferredlocation { get; set; }
        public string track_Prefbatch { get; set; }
        public string track_Reference { get; set; }
        public string track_Wanttojoin { get; set; }
        public string track_WantSMSAlerts { get; set; }
        public string track_LeadAssignedby { get; set; }
        public string track_Status { get; set; }
        public string track_LeadAssignedTo { get; set; }
        public string track_Record_CreatedBy { get; set; }
        public string track_Record_ModifiedBy { get; set; }
        public Nullable<System.DateTime> track_Created_Date { get; set; }
        public Nullable<System.DateTime> track_Modified_Date { get; set; }
        public string track_Website { get; set; }
        public string track_Industry { get; set; }
        public string track_Rating { get; set; }
        public string track_Comment1 { get; set; }
        public string track_Comment2 { get; set; }
        public string track_Comment3 { get; set; }
        public string track_LeadOwner { get; set; }
        public Nullable<System.DateTime> track_LeadDate { get; set; }
        public Nullable<System.DateTime> track_FollowUpdate { get; set; }
        public string track_CommentsForAssignment { get; set; }
        public Nullable<int> track_CompId { get; set; }
        public Nullable<int> track_BrId { get; set; }
        public Nullable<int> track_SelectedProductId { get; set; }
        public Nullable<int> track_SelectedStatusId { get; set; }
        public Nullable<int> track_SelectedReference { get; set; }
        public string track_WantMailAlerts { get; set; }
    }
}
