//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_enquirydetails
    {
        public int detailId { get; set; }
        public int enquiryId { get; set; }
        public string dtl_leadowner { get; set; }
        public string dtl_leadname { get; set; }
        public string dtl_status { get; set; }
        public string dtl_product { get; set; }
        public string dtl_comments { get; set; }
        public Nullable<System.DateTime> dtl_createddt { get; set; }
        public int compId { get; set; }
        public int brId { get; set; }
        public string dtl_maploc_url { get; set; }
        public string dtl_fileloc_folder { get; set; }
        public Nullable<System.DateTime> followup_date { get; set; }
        public Nullable<decimal> dtl_longitude { get; set; }
        public Nullable<decimal> dtl_latitude { get; set; }
    }
}
