//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_campaign
    {
        public int campId { get; set; }
        public string camp_name { get; set; }
        public Nullable<System.DateTime> camp_start_dt { get; set; }
        public Nullable<System.DateTime> camp_end_dt { get; set; }
        public string camp_Category { get; set; }
        public string camp_type { get; set; }
        public string camp_day { get; set; }
        public string camp_product { get; set; }
        public string camp_status { get; set; }
        public string camp_comments { get; set; }
        public int compId { get; set; }
        public int brId { get; set; }
        public string camp_flag { get; set; }
        public Nullable<int> camp_CategoryId { get; set; }
        public Nullable<int> camp_typeId { get; set; }
        public Nullable<int> camp_dayId { get; set; }
        public Nullable<int> camp_productId { get; set; }
        public Nullable<int> camp_statusId { get; set; }
        public Nullable<int> camp_flagId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
