//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FortuneBasicInfo
    {
        public int basic_id { get; set; }
        public int CompId { get; set; }
        public int BrId { get; set; }
        public string OrganizationName { get; set; }
        public string BranchName { get; set; }
        public string LogoPath { get; set; }
        public string OrgEmail { get; set; }
        public string OrgPhone { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> SmsCount { get; set; }
        public Nullable<int> NumberOfUserToAllowed { get; set; }
        public byte[] OrgLogo { get; set; }
        public string email_flag { get; set; }
        public string analytics_flag { get; set; }
        public Nullable<decimal> Email_limit { get; set; }
        public Nullable<decimal> Leads_limit { get; set; }
        public string sms_flag { get; set; }
        public Nullable<decimal> sms_limit { get; set; }
        public string email_alert { get; set; }
        public string sms_alert { get; set; }
    }
}
