//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment
    {
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_mobile { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_actual_cost { get; set; }
        public Nullable<decimal> product_revised_amount { get; set; }
        public string modeof_payment { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> balance_amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<System.DateTime> payment_followupdate { get; set; }
        public Nullable<int> compid { get; set; }
        public Nullable<int> brid { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> modeofpayment_id { get; set; }
        public string comments { get; set; }
    }
}
