//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customlabel
    {
        public int labelId { get; set; }
        public string label_schema_name { get; set; }
        public string label_name { get; set; }
        public int compId { get; set; }
        public int brId { get; set; }
    }
}
