//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Source
    {
        public int SourceId { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<decimal> monthly_budget { get; set; }
        public Nullable<decimal> JanBudgtet { get; set; }
        public Nullable<decimal> FebBudgtet { get; set; }
        public Nullable<decimal> MarBudgtet { get; set; }
        public Nullable<decimal> AprBudgtet { get; set; }
        public Nullable<decimal> MayBudgtet { get; set; }
        public Nullable<decimal> JunBudgtet { get; set; }
        public Nullable<decimal> JulBudgtet { get; set; }
        public Nullable<decimal> AugBudgtet { get; set; }
        public Nullable<decimal> SepBudgtet { get; set; }
        public Nullable<decimal> OctBudgtet { get; set; }
        public Nullable<decimal> NovBudgtet { get; set; }
        public Nullable<decimal> DecBudgtet { get; set; }
    }
}
