//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FortuneRoles
    {
        public tbl_FortuneRoles()
        {
            this.tbl_Menu = new HashSet<tbl_Menu>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
    
        public virtual ICollection<tbl_Menu> tbl_Menu { get; set; }
    }
}
