//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FortuneUsers
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RoleName { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Record_CreatedBy { get; set; }
        public string Record_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<int> IsActiveId { get; set; }
        public string IsActiveName { get; set; }
    }
}
