//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emailtemp
    {
        public int emailtemp_Id { get; set; }
        public string LoginUserName { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string Emailsubject { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> BrId { get; set; }
        public string LeadName { get; set; }
        public string Product { get; set; }
        public string Status { get; set; }
        public string EmailBody { get; set; }
        public string emailtype { get; set; }
        public string alerttype { get; set; }
    }
}
